# Generated by Django 4.1 on 2022-10-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_colors_models_alter_post_color_alter_post_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Models',
            new_name='Model',
        ),
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='auctions.color'),
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
