# Generated by Django 4.1 on 2022-10-21 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_postimages_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='Watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
