# Generated by Django 4.1 on 2022-10-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_post_brand_alter_post_watchlist'),
        ('auctions', '0011_brand_mileage_alter_post_watchlist_post_mileage_and_more'),
    ]

    operations = [
    ]
