# Generated by Django 4.1 on 2022-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phoneNumber',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='social',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
